name: TERRAFORM DESTROY RESOURCES

on:
    workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
      TF_VAR_vm_password: ${{ secrets.TF_VM_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        name: setup-terraform

      - name: terraform init
        run: terraform init

      - name: terraform destroy
        run: terraform destroy -auto-approve
